version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    restart: always
    environment:
      POSTGRES_USER: grafana_user
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: stock_data
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - timescaledb

  ingestor:
    build: .
    container_name: stock_ingestor
    restart: always
    environment:
      - DB_HOST=timescaledb  # Connects directly inside Docker network
    depends_on:
      - timescaledb

volumes:
  timescale_data: